### ISSUE TITLE
Compatibilite with Atom feed format

### ISSUE THREAD

**Issue by ghost** [Misenko/rssnow-plasma5-applet#5]
Hello, I'd like to know if this application is compatible with this feed:
http://feeds.feedburner.com/manjarobrasilfeed
Whenever I try to add this feed in the app they don't show anything and worse, It's like every other feed freezes. I've checked in an online validator to see if this feed follow the default validations:
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2Fmanjarobrasilfeed
And I get a response saying that this is a atom feed format, so this is why I'm asking this.
Sorry my poor english.

**Comment by amarthadan** [comment]
Hi. No, the applet doesn't support Atom feed format at the moment. I hope I'll be able to add the support in the future.
